# Generated by Django 4.2.2 on 2023-07-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=13)),
                ('region', models.CharField(max_length=26)),
                ('surface_area', models.FloatField(default=0.0)),
                ('indep_year', models.SmallIntegerField(blank=True, null=True)),
                ('population', models.IntegerField(default=0)),
                ('life_expectancy', models.FloatField(blank=True, null=True)),
                ('gnp', models.FloatField(blank=True, null=True)),
                ('gnpold', models.FloatField(blank=True, null=True)),
                ('local_name', models.CharField(max_length=45)),
                ('government_form', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(blank=True, max_length=60, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('CountryCode', models.CharField(default='', max_length=3, primary_key=True, serialize=False)),
                ('Language', models.CharField(default='', max_length=30)),
                ('IsOfficial', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('Percentage', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'countrylanguage',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('country_code', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_app.country')),
            ],
        ),
    ]
